#!/bin/bash
name="Eunice Obeko"
state="BenDel"
LGA="Sapele"
PrimarySchool="Triumphant Nursery and Primary School"
SecondarySchool="Lords and Kings Academy"
echo "Name: $name"
echo "State: $state"
echo "LGA: $LGA"
echo "PrimarySchool: $PrimarySchool"
echo "SecondarySchool: $SecondarySchool"
